### PR TITLE
Workaround issue we're having with RHEL 6 not supporting TLS > 1.0

### PR DESCRIPTION
**Pull request by tmclaugh**

### CODE REVIEW

**Comment by aparkinson** [comment]
Amazon Linux is also impacted by this problem

**Comment by tmclaugh** [comment]
Thank you for the heads up! The PRs I've started will fix both. Next stop is fixing our instructions in app and the curl|bash endpoint.

**Comment by tmclaugh** [comment]
@aparkinson if you want to deploy this branch and give me a thumbs up that'll help speed me up.  I can't think of anything that could go wrong in such a small change but I wanted to take some time and think it through.

**Comment by aparkinson** [comment]
@tmclaugh I deployed it a couple of hours ago, it's passed so far

**Pull request merged**
