### PR TITLE
Start Puppet 4 support

### PR DESCRIPTION
**Pull request by tmclaugh**

### CODE REVIEW

**Comment by tmclaugh** [comment]
@tfhartmannif you need this now I'll merge.  If not I want to look at defaulting to Puppet 4 in test-kitchen before merging.

**Comment by tfhartmann** [comment]
@tmclaugh no worries, I can just track the puppet4 branch while I'm testing.

**Comment by tfhartmann** [comment]
Thanks checking this out!

**Comment by tmclaugh** [comment]
@tfhartmann Puppet 4 support merged and now the default.

**Comment by tfhartmann** [comment]
😂  You are my hero!

**Comment by tmclaugh** [comment]
I try Tim.

**Pull request merged**
